# Generated by Django 5.1 on 2024-08-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='nbr_sessions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
