# Generated by Django 5.1 on 2024-08-27 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_location_course_nbr_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tolearn',
            name='desc',
        ),
    ]
