# Generated by Django 5.1 on 2024-08-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tolearn_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='desc',
        ),
    ]
