# Generated by Django 5.1 on 2024-08-28 09:10

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_module_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DONE', 'DONE'), ('PAID', 'PAID')], default=api.models.Status['PENDING'], max_length=20),
        ),
    ]
