# Generated by Django 5.1 on 2024-08-28 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_subscription_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Subscribtion',
        ),
    ]
