# Generated by Django 5.1 on 2024-09-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_subscription_subscribtion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_pixel', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
