version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "80012:8000"
    volumes:
      - ./backend:/backend
    

  frontend:
    build:
      context: ./dashboard
    ports:
      - "30012:3000"
