version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn base.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8012:8000"
    volumes:
      - ./backend:/backend
    

  frontend:
    build:
      context: ./frontend
    ports:
      - "3012:3000"
